import { readFile, writeFile } from "node:fs/promises";
import type { RunRecord } from "./task-state/store.ts";
import { describeWorker } from "./worker/types.ts";

export const BLOCK_START = "<!-- factory:last-run:start -->";
export const BLOCK_END = "<!-- factory:last-run:end -->";

export function renderRunSummary(run: RunRecord): string {
  const worker =
    run.worker === null
      ? "never launched"
      : run.worker.terminatedAt === null
        ? `${describeWorker(run.worker.ref)}, **not terminated**: run \`node factory/cli.ts cleanup ${run.id}\``
        : `${describeWorker(run.worker.ref)}, terminated ${run.worker.terminatedAt}`;
  const lines = [
    "## Last factory run",
    "",
    "Generated by `factory/cli.ts`. Do not edit this block by hand.",
    "",
    `- Run: \`${run.id}\` is **${run.state}**`,
    `- Task: ${run.task.title} (${run.task.repo}, \`${run.task.base}\` to \`${run.branch}\`)`,
    `- Worker: ${worker}`,
    `- PR: ${run.pr === null ? "none" : `[#${run.pr.number}](${run.pr.url}), ${run.pr.state.toLowerCase()}${run.pr.autoMerge ? ", auto-merge on" : ""}`}`,
  ];
  if (run.blocked !== null) {
    lines.push(`- Blocked: ${run.blocked.reason}${run.blocked.question === null ? "" : `. Question: ${run.blocked.question}`}`);
  }
  if (run.error !== null) lines.push(`- Error (${run.error.phase}): ${run.error.message}`);
  lines.push(
    `- States: ${run.history.map((entry) => entry.to).join(" → ")}`,
    `- Time: ${run.createdAt} to ${run.updatedAt}`,
    "- Details: `.factory/state.json`, logs in `.factory/runs/" + run.id + "/`"
  );
  return lines.join("\n");
}

export function replaceBlock(document: string, content: string): string {
  const block = `${BLOCK_START}\n${content}\n${BLOCK_END}`;
  const start = document.indexOf(BLOCK_START);
  const end = document.indexOf(BLOCK_END);
  if (start === -1 || end < start) return `${document.trimEnd()}\n\n${block}\n`;
  return `${document.slice(0, start)}${block}${document.slice(end + BLOCK_END.length)}`;
}

export async function updateHandoff(path: string, run: RunRecord): Promise<void> {
  let document = "# Factory handoff\n";
  try {
    document = await readFile(path, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code !== "ENOENT") throw error;
  }
  await writeFile(path, replaceBlock(document, renderRunSummary(run)));
}
